//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteASPEntities : DbContext
    {
        public WebsiteASPEntities()
            : base("name=WebsiteASPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110250> Brand_2119110250 { get; set; }
        public virtual DbSet<Category_2119110250> Category_2119110250 { get; set; }
        public virtual DbSet<New_2119110250> New_2119110250 { get; set; }
        public virtual DbSet<Order_2119110250> Order_2119110250 { get; set; }
        public virtual DbSet<OrderDetail_2119110250> OrderDetail_2119110250 { get; set; }
        public virtual DbSet<Product_2119110250> Product_2119110250 { get; set; }
        public virtual DbSet<User_2119110250> User_2119110250 { get; set; }
    }
}
