//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order_2119110250
    {
        public int OrderId { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập tên")]
        [Display(Name = "Tên Đơn hàng")]
        public string Name { get; set; }
        [Display(Name = "Sản phẩm")]
        public Nullable<int> ProductId { get; set; }
        [Display(Name = "Giá")]
        public Nullable<double> Price { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<int> Statut { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    }
}
